export const types = {
    SET_ORGANISATION_DATA: 'SET_ORGANISATION_DATA',
    SET_IS_LOADING: 'SET_IS_LOADING',
    SET_SUCCESS :'SET_SUCCESS',
    SET_FAILURE : 'SET_FAILURE',
    SET_USER_IS_FIRST_PART_DONE: 'SET_USER_IS_FIRST_PART_DONE',
    SET_USER_IS_SECOND_PART_DONE: 'SET_USER_IS_SECOND_PART_DONE',
    SET_USER_DATA: 'SET_USER_IS_SECOND_PART_DONE',
}
